
/******************************************************************************
*
*   FILE
*   ----
*   case.c
*
*   History
*   -------
*   2018-10-19   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_ovunity
#define OV_COMPILE_LIBRARY_ovunity
#endif


#include "ovunity.h"
#include "libov/ov_association.h"

#include "libov/ov_macros.h"

OV_IMPL_LINK(ovunity_case)
OV_IMPL_UNLINK(ovunity_case)
OV_IMPL_GETACCESS(ovunity_case)

