
/******************************************************************************
*
*   FILE
*   ----
*   main.c
*
*   History
*   -------
*   2018-07-13   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_ovunity
#define OV_COMPILE_LIBRARY_ovunity
#endif


#include "ovunity.h"
#include "libov/ov_macros.h"
#include "unity.h"
#include "unity_fixture.h"
#include "unity_internals.h"
#include "unity_fixture_internals.h"
#include "ovunity_helper.h"


OV_DLLFNCEXPORT void ovunity_main_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    return;
}

