
/******************************************************************************
 *
 *   FILE
 *   ----
 *   main.c
 *
 *   History
 *   -------
 *   2018-07-13   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/

#ifndef OV_COMPILE_LIBRARY_ovunity
#define OV_COMPILE_LIBRARY_ovunity
#endif

#include "libov/ov_macros.h"
#include "libov/ov_ov.h"

#include "libov/ov_class.h"
#include "libov/ov_path.h"

#include "ovunity.h"
#include "ovunity_helper.h"

#include "unity.h"
#include "unity_fixture.h"
#include "unity_fixture_internals.h"
#include "unity_internals.h"

#define DATAOBJPRE "/data/obj_"
#define DATAENVPRE "/data/env_"

OV_DLLFNCEXPORT OV_RESULT ovunity_main_constructor(OV_INSTPTR_ov_object pobj) {
  /*
   *   local variables
   */
  OV_INSTPTR_ovunity_main pinst = Ov_StaticPtrCast(ovunity_main, pobj);
  OV_RESULT               result;

  /* do what the base class does first */
  result = fb_functionblock_constructor(pobj);
  if(Ov_Fail(result)) return result;

  /* do what */

  return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT ovunity_main_getObjFilePath(
    OV_INSTPTR_ovunity_main pinst, OV_STRING* path, const OV_STRING name) {
  return ov_string_print(path, "%s%s%s.json", pinst->v_sysPath, DATAOBJPRE,
                         name);
}

OV_DLLFNCEXPORT OV_RESULT ovunity_main_getEnvFilePath(
    OV_INSTPTR_ovunity_main pinst, OV_STRING* path, const OV_STRING name) {
  return ov_string_print(path, "%s%s%s.json", pinst->v_sysPath, DATAENVPRE,
                         name);
}

/* writes string to file, if file doesnt exist returns 1 */
OV_DLLFNCEXPORT OV_RESULT ovunity_helper_str2data(const OV_STRING text,
                                                  const OV_STRING filename) {
  if(!text || !filename) {
    return OV_ERR_BADPARAM;
  }
  FILE* handler = fopen(filename, "wb");

  if(handler) {
    fprintf(handler, "%s", text);
    // Always remember to close the file.
    fclose(handler);
    return 0;
  } else {
    ov_logfile_error("couldnt open file: %s", filename);
  }
  return 1;
}

OV_DLLFNCEXPORT OV_STRING ovunity_helper_data2str(OV_STRING filename) {
  OV_STRING buffer = NULL;
  long int  string_size, read_size;
  FILE*     handler = fopen(filename, "rb");

  if(handler) {
    // Seek the last byte of the file
    fseek(handler, 0, SEEK_END);
    // Offset from the first to the last byte, or in other words, filesize
    string_size = ftell(handler);
    // go back to the start of the file
    rewind(handler);

    // Allocate a string that can hold it all
    buffer = (OV_STRING)Ov_HeapMalloc(sizeof(char) * (string_size + 1));

    // Read it all in one operation
    read_size = fread(buffer, sizeof(char), string_size, handler);

    // fread doesn't set it so put a \0 in the last position
    // and buffer is now officially a string
    buffer[string_size] = '\0';

    if(string_size != read_size) {
      // Something went wrong, throw away the memory and set
      // the buffer to NULL
      ov_string_setvalue(&buffer, NULL);
      fclose(handler);
      Throw(OV_ERR_GENERIC);
    }

    // Always remember to close the file.
    fclose(handler);
  } else {
    Throw(OV_ERR_BADPATH);
  }

  return buffer;
}

OV_DLLFNCEXPORT void ovunity_loadEnv(const OV_INSTPTR_ovunity_main pinst,
                                     const OV_STRING               what,
                                     const OV_STRING               where) {
  /* getting libname and classname */
  OV_INSTPTR_ov_domain pclass = Ov_GetParent(ov_instantiation, pinst);
  OV_STRING            classname = ov_strdup(pclass->v_identifier);
  OV_INSTPTR_ov_object plib = Ov_GetParent(ov_containment, pclass);
  OV_STRING            projname = ov_strdup(plib->v_identifier);

  OV_STRING dataPath = NULL;
  char*     ahome = getenv("ACPLT_HOME");
  ov_string_print(&dataPath, "%s/dev/%s/test/%s/%s", ahome, projname, classname,
                  what);
  ovunity_loadJsonAsTree(dataPath, where);
  ov_free(classname);
  ov_free(projname);
  return;
}

OV_DLLFNCEXPORT void ovunity_loadJsonAsTree(const OV_STRING what,
                                            const OV_STRING where) {
  OV_RESULT result = OV_ERR_OK;
  // TODO: check json value
  OV_INSTPTR_CTree_Download pdownload = NULL;

  result =
      Ov_CreateIDedObject(CTree_Download, pdownload, &pdb->root, "Download");
  if(Ov_Fail(result)) {
    ov_logfile_error("%u: %s:", result, ov_result_getresulttext(result));
    Throw(result);
    return;
  }

  ov_memstack_lock();
  OV_STRING tmpStr = ovunity_helper_data2str(what);
  ov_string_print(&pdownload->v_json, tmpStr);
  ov_string_print(&pdownload->v_path, where);
  pdownload->v_force = 1;
  result = CTree_Download_execute(pdownload);
  Ov_DeleteObject(pdownload);
  Ov_HeapFree(tmpStr);
  if(Ov_Fail(result)) {
    ov_logfile_error("%u: %s: ovunity_loadJsonAsTree: CTree failed", result,
                     ov_result_getresulttext(result));
    ov_memstack_unlock();
    Throw(result);
    return;
  }
  ov_memstack_unlock();
  return;
}

/* creates case with case_name under pinst and links, returns NULL in case of
 * failure */
OV_DLLFNCEXPORT OV_INSTPTR_ovunity_ovCase
                ovunity_createCase(OV_INSTPTR_ovunity_main pinst, const OV_STRING case_name) {
  OV_RESULT                 result = OV_ERR_OK;
  OV_INSTPTR_ovunity_ovCase pcase = NULL;
  result = Ov_CreateObject(ovunity_ovCase, pcase, pinst, case_name);
  if(result) {
    ov_logfile_error("couldt create case: %u : %s", result,
                     ov_result_getresulttext(result));
    return NULL;
  }
  pcase->v_sysPath = NULL;
  ov_string_print(&pcase->v_sysPath, "%s/%s", pinst->v_sysPath, case_name);
  result = Ov_Link(ovunity_case, pinst, pcase);
  if(result) {
    ov_logfile_error("couldt link case with tester: %u : %s", result,
                     ov_result_getresulttext(result));
    Ov_DeleteObject(pcase);
    return NULL;
  }
  return pcase;
}

/* getting case path */
/*
 * gives path under the object to simulate environment
 */
/* if case with name case_name doesnt exist returns NULL */
OV_DLLFNCEXPORT OV_STRING ovunity_getCasePath(
    const OV_INSTPTR_ovunity_main pinst, const OV_STRING case_name) {
  OV_STRING                 path = NULL;
  OV_INSTPTR_ovunity_ovCase pcase = NULL;
  pcase = Ov_SearchChildEx(ovunity_case, pinst, case_name, ovunity_ovCase);
  if(pcase)
    ov_string_setvalue(&path, ov_path_getcanonicalpath((void*)pcase, 2));
  return path;
}

OV_DLLFNCEXPORT void ovunity_main_typemethod(OV_INSTPTR_fb_functionblock pfb,
                                             OV_TIME*                    pltc) {
  /*
   *   local variables
   */
  return;
}
