
/******************************************************************************
*
*   FILE
*   ----
*   Node.c
*
*   History
*   -------
*   2018-06-08   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_wandelbareTopologie
#define OV_COMPILE_LIBRARY_wandelbareTopologie
#endif


#include "wandelbareTopologie.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT void wandelbareTopologie_Node_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_wandelbareTopologie_Node pinst = Ov_StaticPtrCast(wandelbareTopologie_Node, pfb);

    return;
}

