
/******************************************************************************
*
*   FILE
*   ----
*   main.c
*
*   History
*   -------
*   2018-08-03   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_ovhelper
#define OV_COMPILE_LIBRARY_ovhelper
#endif


#include "ovhelper.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT void ovhelper_main_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_ovhelper_main pinst = Ov_StaticPtrCast(ovhelper_main, pfb);

    return;
}

