
/******************************************************************************
*
*   FILE
*   ----
*   dsync.c
*
*   History
*   -------
*   2018-08-02   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sync
#define OV_COMPILE_LIBRARY_sync
#endif


#include "sync.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT sync_dsync_reset_set(
    OV_INSTPTR_sync_dsync          pobj,
    const OV_BOOL  value
) {
    pobj->v_reset = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void sync_dsync_startup(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sync_dsync pinst = Ov_StaticPtrCast(sync_dsync, pobj);

    /* do what the base class does first */
    fb_functionblock_startup(pobj);

    /* do what */


    return;
}

OV_DLLFNCEXPORT void sync_dsync_shutdown(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sync_dsync pinst = Ov_StaticPtrCast(sync_dsync, pobj);

    /* do what */

    /* set the object's state to "shut down" */
    fb_functionblock_shutdown(pobj);

    return;
}

OV_DLLFNCEXPORT void sync_dsync_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sync_dsync pinst = Ov_StaticPtrCast(sync_dsync, pfb);

    return;
}

