/******************************************************************************
 *
 *   FILE
 *   ----
 *   dsync.c
 *
 *   History
 *   -------
 *   2018-08-02   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/

#ifndef OV_COMPILE_LIBRARY_sync
#define OV_COMPILE_LIBRARY_sync
#endif

#include "CTree.h"
#include "PostSys.h"
#include "ksbase_helper.h"
#include "libov/ov_macros.h"
#include "libov/ov_path.h"
#include "libov/ov_result.h"
#include "object_helper.h"
#include "sync.h"

#include "sync_helper.h"

#include "ksapi_commonFuncs.h"

#include "sync.ovt"

#define SYNC_SRC_INIT 0
#define SYNC_SRC_SYNCCREATEREQUESTED 1
#define SYNC_SRC_TRANSPORTREQUESTED 2
#define SYNC_SRC_DONE 4
#define SYNC_SRC_ERROR 64

const OV_STRING classesToConfiugure[] = {[FBCOMLIBSET] = "fbcomlib/setVar",
                                         [FBCOMLIBGET] = "fbcomlib/getVar",
                                         [KSAPIGET] = "ksapi/getVar",
                                         [KSAPISET] = "ksapi/setVar"};

OV_DLLFNCEXPORT OV_RESULT sync_dsync_reset_set(OV_INSTPTR_sync_dsync pobj,
                                               const OV_BOOL         value) {
  pobj->v_reset = value;
  return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sync_dsync_shutdown_set(OV_INSTPTR_sync_dsync pobj,
                                                  const OV_BOOL         value) {
  OV_RESULT result = OV_ERR_OK;
  pobj->v_reset = value;
  if(value) {
    OV_INSTPTR_ov_object proot = ov_path_getobjectpointer(pobj->v_srcPath, 2);
    if(!proot) { // todo badparam info
      ov_logfile_error("root couldt be found");
      pobj->v_result = OV_ERR_GENERIC;
      return 0;
    }
    // shutting down
    for(OV_UINT i = 0; i < SYNC_CONFIGURE_LEN; ++i) {
      if(i == FBCOMLIBGET || i == KSAPIGET) continue;
      OV_INSTPTR_ov_class pssc = ov_class_search(classesToConfiugure[i]);
      if(pssc) {
        OV_INSTPTR_ov_object pobj = NULL;
        Ov_ForEachChild(ov_instantiation, pssc, pobj) {
          /* checking if right one */
          if(object_isDescendant(proot, Ov_StaticPtrCast(ov_object, pobj))) {
            /* if(i == FBCOMLIBSET) */
            /*   Ov_StaticPtrCast(fbcomlib_setVar, pobj)->v_actimode = 0; */
            /* else if(i == KSAPISET) { */
            OV_INSTPTR_sync_getSetAdapt pMsgCrtr = NULL;
            Ov_ForEachChildEx(ov_containment, Ov_StaticPtrCast(ov_domain, pobj),
                              pMsgCrtr, sync_getSetAdapt) {
              break;
            };

            if(!pMsgCrtr) {
              ov_logfile_warning("%s has no msgCreatorchild",
                                 pobj->v_identifier);
              continue;
            }
            pMsgCrtr->v_actimode = 0;
            ov_logfile_info("%s.actimode = 0", pMsgCrtr->v_identifier);
          }
        }
      }
    }
  }
  pobj->v_status = SYNC_SRC_DONE;
  ov_logfile_info("dsync shutdown on src site.");
  return OV_ERR_OK;
}

OV_INSTPTR_sync_getSetAdapt dsync_createSetVarAlt(OV_INSTPTR_sync_dsync pinst,
                                                  OV_INSTPTR_ov_object  pobj) {
  OV_RESULT                   result = OV_ERR_OK;
  OV_INSTPTR_sync_getSetAdapt pMsgCrtr = NULL;
  OV_STRING                   dstHost = NULL;
  OV_STRING                   dstServer = NULL;
  OV_STRING                   dstInst = NULL;
  OV_STRING                   dstHostPort = NULL;
  OV_STRING                   dstServerPort = NULL;

  OV_INSTPTR_fb_task pUrtask =
      Ov_StaticPtrCast(fb_task, ov_path_getobjectpointer("/Tasks/UrTask", 2));
  if(!pUrtask) {
    ov_logfile_error("urtask couldnt found");
    return NULL;
  }
  result = ks_splitOneStringPath(pinst->v_destKS, &dstHost, &dstHostPort,
                                 &dstServer, &dstServerPort, &dstInst);
  if(Ov_Fail(result)) {
    ov_logfile_error("%u: %s:", result, ov_result_getresulttext(result));
    return NULL;
  }

  if(Ov_CanCastTo(fbcomlib_setVar, pobj)) {
    OV_INSTPTR_fbcomlib_setVar pobjCasted =
        Ov_StaticPtrCast(fbcomlib_setVar, pobj);
    result =
        Ov_CreateIDedObject(sync_getSetAdapt, pMsgCrtr, pobjCasted, "MsgCrtr");
    if(result) {
      // todo info
      ov_logfile_info("%s", ov_result_getresulttext(result));
      return NULL;
    }

    result = Ov_Link(fb_tasklist, pobjCasted, pMsgCrtr);
    if(Ov_Fail(result)) {
      ov_logfile_error("%u: %s: couldnt link fbsetvar_alt to fbsetvar", result,
                       ov_result_getresulttext(result));
      return NULL;
    }
    pMsgCrtr->v_actimode = 1;
    pMsgCrtr->v_iexreq = 1;

    PostSys_msgCreator_pathLen_set(
        Ov_StaticPtrCast(PostSys_msgCreator, pMsgCrtr), 2);
    pMsgCrtr->v_type = 0;

    ov_string_setvalue(&pMsgCrtr->v_receiverHost.value[0], dstHost);
    ov_string_setvalue(&pMsgCrtr->v_receiverName.value[0], dstServer);
    ov_string_setvalue(&pMsgCrtr->v_receiverInstance.value[0],
                       PLAYER_SRCNODE_PATH_DEST);

    ov_string_setvalue(&pMsgCrtr->v_receiverHost.value[1], pobjCasted->v_host);
    ov_string_setvalue(&pMsgCrtr->v_receiverName.value[1],
                       pobjCasted->v_server);
    ov_string_setvalue(&pMsgCrtr->v_instancePath, pobjCasted->v_path);
    ov_string_setvalue(&pMsgCrtr->v_receiverInstance.value[1],
                       DEFAULT_POSTSYS_EXECUTER);
    pobjCasted->v_doSend = 0;
    pobjCasted->v_doCyclic = 0;

    /* ov_string_setvalue(&pobjCasted->v_host, "localhost"); */
    /* // TODO: 'echo $USER:' change MANAGER to current Server Name '!v */
    /* // strftime("%c") */
    /* ov_string_setvalue(&pobjCasted->v_server, "MANAGER"); */
    /* ov_string_setvalue( */
    /*     &pobjCasted->v_path, */
    /*     ov_path_getcanonicalpath(Ov_StaticPtrCast(ov_object, pMsgCrtr), 2));
     */

    /* ov_string_append(&pobjCasted->v_path, MSGCREATOR_TRIGGER); */

  } else if(Ov_CanCastTo(fbcomlib_getVar, pobj)) {
    OV_INSTPTR_fbcomlib_getVar pobjCasted =
        Ov_StaticPtrCast(fbcomlib_getVar, pobj);
    result =
        Ov_CreateIDedObject(sync_getSetAdapt, pMsgCrtr, pobjCasted, "MsgCrtr");
    if(result) {
      // todo info
      ov_logfile_info("%s", ov_result_getresulttext(result));
      return NULL;
    }

    PostSys_msgCreator_pathLen_set(
        Ov_StaticPtrCast(PostSys_msgCreator, pMsgCrtr), 2);
    pMsgCrtr->v_type = 1;
    ov_string_setvalue(&pMsgCrtr->v_receiverHost.value[0], dstHost);
    ov_string_setvalue(&pMsgCrtr->v_receiverName.value[0], dstServer);
    ov_string_setvalue(&pMsgCrtr->v_receiverInstance.value[0],
                       PLAYER_SRCNODE_PATH_DEST);

    ov_string_setvalue(&pMsgCrtr->v_receiverHost.value[1], pobjCasted->v_host);
    ov_string_setvalue(&pMsgCrtr->v_receiverName.value[1],
                       pobjCasted->v_server);
    ov_string_setvalue(&pMsgCrtr->v_instancePath, pobjCasted->v_path);
    ov_string_setvalue(&pMsgCrtr->v_receiverInstance.value[1],
                       DEFAULT_POSTSYS_EXECUTER);

    ov_string_setvalue(&pobjCasted->v_host, "localhost");
    // TODO: 'echo $USER:' change MANAGER to current Server Name '!v
    // strftime("%c")
    ov_string_setvalue(&pobjCasted->v_server, "MANAGER");
    ov_string_setvalue(
        &pobjCasted->v_path,
        ov_path_getcanonicalpath(Ov_StaticPtrCast(ov_object, pMsgCrtr), 2));
    ov_string_append(&pobjCasted->v_path, MSGCREATOR_TRIGGER);
  } else if(Ov_CanCastTo(ksapi_setVar, pobj)) {
    if(Ov_CanCastTo(fbcomlib_setVar, pobj->v_pouterobject)) {
      ov_logfile_warning("%s part of fbcomlib_setvar", pobj->v_identifier);
      return NULL;
    };
    OV_INSTPTR_ksapi_setVar pobjCasted = Ov_StaticPtrCast(ksapi_setVar, pobj);
    result =
        Ov_CreateIDedObject(sync_getSetAdapt, pMsgCrtr, pobjCasted, "MsgCrtr");
    if(result) {
      // todo info
      ov_logfile_info("%s", ov_result_getresulttext(result));
      return NULL;
    }
    PostSys_msgCreator_pathLen_set(
        Ov_StaticPtrCast(PostSys_msgCreator, pMsgCrtr), 2);

    pMsgCrtr->v_type = 0;
    ov_string_setvalue(&pMsgCrtr->v_receiverHost.value[0], dstHost);
    ov_string_setvalue(&pMsgCrtr->v_receiverName.value[0], dstServer);
    ov_string_setvalue(&pMsgCrtr->v_receiverInstance.value[0],
                       PLAYER_SRCNODE_PATH_DEST);

    ov_string_setvalue(&pMsgCrtr->v_receiverHost.value[1],
                       pobjCasted->v_serverHost);
    ov_string_setvalue(&pMsgCrtr->v_receiverName.value[1],
                       pobjCasted->v_serverName);
    ov_string_setvalue(&pMsgCrtr->v_instancePath, pobjCasted->v_path);
    ov_string_setvalue(&pMsgCrtr->v_receiverInstance.value[1],
                       DEFAULT_POSTSYS_EXECUTER);

    ov_string_setvalue(&pobjCasted->v_serverHost, "localhost");
    // TODO: 'echo $USER:' change MANAGER to current Server Name '!v
    // strftime("%c")
    ov_string_setvalue(&pobjCasted->v_serverName, "MANAGER");
    ov_string_setvalue(
        &pobjCasted->v_path,
        ov_path_getcanonicalpath(Ov_StaticPtrCast(ov_object, pMsgCrtr), 2));
    ov_string_append(&pobjCasted->v_path, MSGCREATOR_TRIGGER);
  } else if(Ov_CanCastTo(ksapi_getVar, pobj)) {
    OV_INSTPTR_ksapi_getVar pobjCasted = Ov_StaticPtrCast(ksapi_getVar, pobj);
    result =
        Ov_CreateIDedObject(sync_getSetAdapt, pMsgCrtr, pobjCasted, "MsgCrtr");
    if(result) {
      // todo info
      ov_logfile_info("%s", ov_result_getresulttext(result));
      return NULL;
    }
    PostSys_msgCreator_pathLen_set(
        Ov_StaticPtrCast(PostSys_msgCreator, pMsgCrtr), 2);

    pMsgCrtr->v_type = 1;
    ov_string_setvalue(&pMsgCrtr->v_receiverHost.value[0], dstHost);
    ov_string_setvalue(&pMsgCrtr->v_receiverName.value[0], dstServer);
    ov_string_setvalue(&pMsgCrtr->v_receiverInstance.value[0],
                       PLAYER_SRCNODE_PATH_DEST);

    ov_string_setvalue(&pMsgCrtr->v_receiverHost.value[1],
                       pobjCasted->v_serverHost);
    ov_string_setvalue(&pMsgCrtr->v_receiverName.value[1],
                       pobjCasted->v_serverName);
    ov_string_setvalue(&pMsgCrtr->v_instancePath, pobjCasted->v_path);
    ov_string_setvalue(&pMsgCrtr->v_receiverInstance.value[1],
                       DEFAULT_POSTSYS_EXECUTER);

    ov_string_setvalue(&pobjCasted->v_serverHost, "localhost");
    // TODO: 'echo $USER:' change MANAGER to current Server Name '!v
    // strftime("%c")
    ov_string_setvalue(&pobjCasted->v_serverName, "MANAGER");
    ov_string_setvalue(
        &pobjCasted->v_path,
        ov_path_getcanonicalpath(Ov_StaticPtrCast(ov_object, pMsgCrtr), 2));
    ov_string_append(&pobjCasted->v_path, MSGCREATOR_TRIGGER);
  } else {
    ov_logfile_error("%s is not from right class", pobj->v_identifier);
    return NULL;
  }

  return pMsgCrtr;
}

OV_DLLFNCEXPORT void sync_dsync_typemethod(OV_INSTPTR_fb_functionblock pfb,
                                           OV_TIME*                    pltc) {
  /*
   *   local variables
   */
  OV_INSTPTR_sync_dsync pinst = Ov_StaticPtrCast(sync_dsync, pfb);

  OV_RESULT result = OV_ERR_OK;

  OV_STRING                  dsyncDstPath = "/data/dsyncDst";
  OV_STRING                  dstName = NULL;
  OV_STRING                  dstHost = NULL;
  OV_INSTPTR_CTree_Transport ptrans =
      Ov_StaticPtrCast(CTree_Transport, &pinst->p_transport);
  OV_INSTPTR_sync_dsyncDst pdsyncDst = &pinst->p_dsyncDstTemp;
  OV_INSTPTR_ov_object     proot = NULL;

  switch(pinst->v_status) {
    case SYNC_SRC_INIT:
      /* check */
      ov_memstack_lock();
      proot = ov_path_getobjectpointer(pinst->v_srcPath, 2);
      if(!proot) { // todo badparam info
        ov_logfile_error("root couldt be found");
        pinst->v_status = SYNC_SRC_ERROR;
        ov_memstack_unlock();
        return;
      } /* configure dest server */
      pinst->p_ksCrtObj.v_path = NULL;
      ov_memstack_lock();
      ks_splitOneStringPath(pinst->v_destKS, &dstHost, NULL, &dstName, NULL,
                            NULL);
      ov_string_print(&ptrans->v_targetKS, "//%s/%s%s", dstHost, dstName,
                      dsyncDstPath);
      ov_memstack_unlock();

      ov_string_print(
          &pdsyncDst->v_srcKS, "//%s/%s%s", pinst->v_selfHost,
          pinst->v_selfServer,
          ov_path_getcanonicalpath(Ov_StaticPtrCast(ov_object, pinst), 2));

      ov_string_setvalue(&pdsyncDst->p_syncDownload.v_srcPath,
                         pinst->v_srcPath);
      ov_string_setvalue(
          &ptrans->v_path,
          ov_path_getcanonicalpath(Ov_StaticPtrCast(ov_object, pdsyncDst), 2));
      CTree_Transport_typemethod(Ov_StaticPtrCast(fb_functionblock, ptrans),
                                 NULL);
      pinst->v_status = SYNC_SRC_SYNCCREATEREQUESTED;
      ov_logfile_info("sync on destination requested");
      return;
      break;
    case SYNC_SRC_SYNCCREATEREQUESTED:
      /* if(pkscrt->v_status & KSAPI_COMMON_EXTERNALERROR & */
      /*    KSAPI_COMMON_INTERNALERROR) { */
      /*   pinst->v_status = SYNC_SRC_ERROR; */
      /*   ov_logfile_error("Error at ksapi"); */
      /*   pinst->v_result = OV_ERR_GENERIC; */
      /*   return; */
      /* } else if(pkscrt->v_status & KSAPI_COMMON_WAITINGFORANSWER) { */
      /*   return; */
      /* } else if(pkscrt->v_status & KSAPI_COMMON_REQUESTCOMPLETED) { */
      /* configure setvar & getvar */
      result = ptrans->v_result;
      if(Ov_Fail(result)) {
        if(result != OV_ERR_ALREADYEXISTS) {
          ov_logfile_error("%u: %s: ksapi dsyncDst creation unsuccessful",
                           result, ov_result_getresulttext(result));
          pinst->v_result = result;
          return;
        } else {
          ov_logfile_warning("%u: %s: dsyncDst", result,
                             ov_result_getresulttext(result));
        }
      }
      ov_logfile_info("dsyncDst created successfully. Transporting...");
      /* } */
      // setvar
      for(OV_UINT i = 0; i < SYNC_CONFIGURE_LEN; ++i) {
        OV_INSTPTR_ov_class pssc = ov_class_search(classesToConfiugure[i]);
        if(pssc) {
          OV_INSTPTR_ov_object pobj = NULL;
          Ov_ForEachChild(ov_instantiation, pssc, pobj) {
            /* checking if right one */
            if(object_isDescendant(proot, Ov_StaticPtrCast(ov_object, pobj))) {
              /* create Msg alternative */
              OV_INSTPTR_sync_getSetAdapt pMsgCrtr =
                  dsync_createSetVarAlt(pinst, pobj);
              if(!pMsgCrtr) { // todo info
                              //				ov_logfile_error("couldnt
                              // create
                              // setvar_alt %s", pobj->v_identifier);

                // TODO: zzz: handle if no msgcreater created Mo 03 Dez 2018
                // 16:24:17 CET

                /* ov_memstack_unlock(); */
                /* return; */
              }
            }
          }
        } else {
          ov_logfile_info("fbcomlib/setVar not used");
        }
      }
      ov_logfile_info("setgetalternate creation done.");

      /* run transport */
      OV_INSTPTR_CTree_Transport ptrans =
          Ov_StaticPtrCast(CTree_Transport, &pinst->p_transport);
      ov_string_setvalue(&ptrans->v_path, pinst->v_srcPath);
      ov_string_setvalue(&ptrans->v_targetKS, pinst->v_destKS);
      ov_string_print(&ptrans->v_targetDownloadPath, "%s%s", DSYNC_PATH_DEST,
                      DSYNC_DOWNLOAD_PATH_DEST_EXT);
      CTree_Transport_typemethod(Ov_StaticPtrCast(fb_functionblock, ptrans),
                                 NULL);
      pinst->v_status = SYNC_SRC_TRANSPORTREQUESTED;
      ov_logfile_info("transport requested");
      return;
      break;
    case SYNC_SRC_TRANSPORTREQUESTED:
      // todo
      if(pinst->p_transport.v_status == 3) {
        ov_logfile_info("transport done successfully");
      } else {
        ov_logfile_error("sync failed at transport");
        pinst->v_status = SYNC_SRC_ERROR;
      }
      break;
    case SYNC_SRC_DONE: ov_logfile_info("sync in SYNC_SRC_DONE"); break;
    case SYNC_SRC_ERROR: pinst->v_actimode = 0; break;
    default: // TODO: zzz: give more info and set Do 29 Nov 2018 16:20:10 CET
      ov_memstack_unlock();
      return;
  }
  /* wait for command */
  ov_memstack_unlock();
  return;
}
