/******************************************************************************
 *
 *   FILE
 *   ----
 *   dummy.c
 *
 *   History
 *   -------
 *   2018-11-14   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/

#ifndef OV_COMPILE_LIBRARY_sync
#define OV_COMPILE_LIBRARY_sync
#endif

#include "libov/ov_macros.h"
#include "sync.h"

OV_DLLFNCEXPORT OV_RESULT sync_dummy_IN1_set(OV_INSTPTR_sync_dummy pobj,
                                             const OV_ANY*         value) {
  ov_logfile_info("%s.IN1 set called", pobj->v_identifier);
  return ov_variable_setanyvalue(&pobj->v_IN1, value);
}

OV_DLLFNCEXPORT OV_ANY* sync_dummy_IN1_get(OV_INSTPTR_sync_dummy pobj) {
  ov_logfile_info("%s.IN1 get called", pobj->v_identifier);
  return &pobj->v_IN1;
}

/* OV_DLLFNCEXPORT OV_RESULT sync_dummy_IN1_set(OV_INSTPTR_sync_dummy pobj, */
/*                                              const OV_ANY          value) {
 */
/*   pobj->v_IN1 = value; */
/*   return OV_ERR_OK; */
/* } */

OV_DLLFNCEXPORT void sync_dummy_typemethod(OV_INSTPTR_fb_functionblock pfb,
                                           OV_TIME*                    pltc) {
  /*
   *   local variables
   */
  /*OV_INSTPTR_sync_dummy pinst = Ov_StaticPtrCast(sync_dummy, pfb);*/

  return;
}

