/******************************************************************************
 *
 *   FILE
 *   ----
 *   syncVars.c
 *
 *   History
 *   -------
 *   2018-09-24   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/

#ifndef OV_COMPILE_LIBRARY_sync
#define OV_COMPILE_LIBRARY_sync
#endif

#include "sync.h"
#include "libov/ov_macros.h"
#include "CException.h"
#include "NoneTicketAuthenticator.h"

#define FBCOMLIB_STATE_INIT				0
#define FBCOMLIB_STATESTR_INIT			"initial state"

#define FBCOMLIB_STATE_WAITING			1
#define FBCOMLIB_STATESTR_WAITING		"request sent, awaiting answer"

#define FBCOMLIB_STATE_OK				2
#define FBCOMLIB_STATESTR_OK			"OK"

#define FBCOMLIB_STATE_WRONGINPUT		4
#define FBCOMLIB_STATESTR_WRONGINPUT	"invalid input variables"

#define FBCOMLIB_STATE_INTERNAL_ERROR	8
#define FBCOMLIB_STATESTR_INTERNAL_ERROR	"internal error"

#define FBCOMLIB_STATE_KSAPI_ERROR		16
#define FBCOMLIB_STATESTR_KSAPI_ERROR	"ksapi error"

#define FBCOMLIB_STATE_EXTERNAL_ERROR	32
#define FBCOMLIB_STATESTR_EXTERNAL_ERROR	"external error"

#define FBCOMLIB_STATE_TIMEOUT			64
#define FBCOMLIB_STATESTR_TIMEOUT		"request timed out"

#define FBCOMLIB_STATE_UNKNOWN_ERROR	128
#define FBCOMLIB_STATESTR_UNKNOWN_ERROR	"unknown error"

void sync_syncVars_refreshVars(OV_INSTPTR_sync_syncVars pinst) {
	OV_INSTPTR_sync_syncVar pvar = NULL;
	OV_TICKET *pticket = NULL;

	OV_GETVAR_PAR get_var_par = { 0, 0, NULL };
	OV_GETVAR_RES get_var_res = { 0, NULL };
	OV_GETVAR_ITEM *one_result;
	OV_UINT numOfVars = 0;

	OV_RESULT res = OV_ERR_OK;
	OV_STRING tmpStr = NULL;

	OV_TIME pltc = { 0 };
	ov_time_gettime(&pltc);

	// create NONE-ticket
	pticket = ksbase_NoneAuth->v_ticket.vtbl->createticket(NULL, OV_TT_NONE);
	Ov_ForEachChild(fbcomlib_PkgVar, pinst, pvar)
	{
		numOfVars++;
	}
	ov_memstack_lock();
	OV_STRING* var_path = ov_memstack_alloc(numOfVars * sizeof(OV_STRING));
	OV_UINT j = 0;
	Ov_ForEachChild(fbcomlib_PkgVar, pinst, pvar)
	{
		var_path[j++] = pvar->v_sourcePath;
	}
	get_var_par.identifiers_len = numOfVars;
	get_var_par.identifiers_val = var_path;
	ov_ksserver_getvar(2, pticket, &get_var_par, &get_var_res);

	pinst->v_opResult = get_var_res.result;
	if(Ov_Fail(get_var_res.result)) {
		ov_logfile_error("%s: from ks : %s",
			ov_result_getresulttext(get_var_res.result), var_path);
		ov_string_setvalue(&var_path, NULL);
	} else {
		j = 0;
		Ov_ForEachChild(fbcomlib_PkgVar, pinst, pvar)
		{
			if(j >= get_var_res.items_len) {
				ov_logfile_error("more vars than get");
				break;
			}
			if(Ov_Fail(get_var_res.items_val[j].result)) {
				ov_logfile_error("%s: from ks :%s",
					ov_result_getresulttext(get_var_res.items_val[j].result), var_path);
				ov_string_setvalue(&var_path, NULL);
			}
			pvar->v_varResult = get_var_res.items_val[j].result;
			ov_variable_setanyvalue(&pvar->v_value,
				&get_var_res.items_val[j].var_current_props);
			fbcomlib_pkgSetVariable_typemethod(pvar, &pltc);
			j++;
		}
	}
	ov_memstack_unlock();
	return;
}
/*
 *	Compare two any variable values, result is greater than, equal to or less than zero
 */
OV_INT ov_varvalue_compare(OV_VAR_VALUE* v1, OV_VAR_VALUE* v2) {
	switch (v1->vartype) {
		case OV_VT_STRING:
			if(v1->vartype != OV_VT_STRING) Throw(OV_ERR_BADPARAM);
			return ov_string_compare(v1->valueunion.val_string,
				v1->valueunion.val_string);
			break;
		default:
			Throw(OV_ERR_BADPARAM);
	}
}

void sync_syncVars_seperateUnchangedVars(OV_INSTPTR_sync_syncVars pinst) {
	OV_INSTPTR_sync_syncVar pvar = NULL;

	Ov_ForEachChildEx(fbcomlib_PkgVar, pinst, pvar, sync_syncVar)
	{
		if(ov_varvalue_compare(&pvar->v_value.value,
			&pvar->v_lastSentValue.value)) {
			Ov_Link(ksapi_operationToVariable, &pinst->p_apiSet, &pvar->p_apiVar);
			ov_logfile_info("Linking: %s changed from %s to %s", pvar->v_identifier,
				pvar->v_lastSentValue.value.valueunion.val_string,
				pvar->v_value.value.valueunion.val_string);
		} else {
			Ov_Unlink(ksapi_operationToVariable, &pinst->p_apiSet, &pvar->p_apiVar);
			ov_logfile_info("Unlinking: %s is not changed at %s and %s",
				pvar->v_identifier,
				pvar->v_lastSentValue.value.valueunion.val_string,
				pvar->v_value.value.valueunion.val_string);
		}
	}
}
void updateLastChanged(OV_INSTPTR_sync_syncVars pinst) {
	return;
}

OV_DLLFNCEXPORT void sync_syncVars_typemethod(OV_INSTPTR_fb_functionblock pfb,
		OV_TIME *pltc) {
	/*
	 *   local variables
	 */
	OV_INSTPTR_sync_syncVars pinst = Ov_StaticPtrCast(sync_syncVars, pfb);

	OV_RESULT result = OV_ERR_OK;
	CEXCEPTION_T err;
	Try
			{
				/* executing send*/

				//	switch (pinst->v_state) {
				//		case FBCOMLIB_STATE_OK:
				//		case FBCOMLIB_STATE_INIT:
				//		case FBCOMLIB_STATE_WAITING:
				//		case FBCOMLIB_STATE_WRONGINPUT:
				//		case FBCOMLIB_STATE_INTERNAL_ERROR:
				//		case FBCOMLIB_STATE_EXTERNAL_ERROR:
				//		case FBCOMLIB_STATE_KSAPI_ERROR:
				//			fbcomlib_setVar_typemethod(pinst, &pltc);
				//		case FBCOMLIB_STATE_TIMEOUT:
				//		case FBCOMLIB_STATE_UNKNOWN_ERROR:
				//		default:
				//			return 1;
				//	}
				/*
				 *   local variables
				 */
				OV_VTBLPTR_ksapi_setVar pVtblSetVar =
						(OV_VTBLPTR_ksapi_setVar) pclass_ksapi_setVar->v_pvtable;

				if(pinst->v_state == FBCOMLIB_STATE_WAITING) { /*	waiting: calculate timeouts and check ksapi-object for answer	*/
					fbcomlib_setVar_typemethod(pinst, pltc);
					if(pinst->v_state
							& (FBCOMLIB_STATE_EXTERNAL_ERROR
									| FBCOMLIB_STATE_INTERNAL_ERROR
									| FBCOMLIB_STATE_TIMEOUT
									| FBCOMLIB_STATE_KSAPI_ERROR
									| FBCOMLIB_STATE_UNKNOWN_ERROR))
					Throw(pinst->v_state);
				}

				if((pinst->v_state == FBCOMLIB_STATE_OK)
						|| (pinst->v_state == FBCOMLIB_STATE_INIT)) { /*	ready to start	*/
					if(pinst->v_sendRequested) { /*	single send requested	*/
						result = ov_string_setvalue(&(pinst->p_apiSet.v_serverHost),
							pinst->v_host);
						if(Ov_Fail(result)) {
							pinst->v_errorCode = result;
							fbcomlib_FBComCommon_state_set(
								Ov_StaticPtrCast(fbcomlib_FBComCommon, pinst),
								FBCOMLIB_STATE_INTERNAL_ERROR);
							Throw(result);
						}
						result = ov_string_setvalue(&(pinst->p_apiSet.v_serverName),
							pinst->v_server);
						if(Ov_Fail(result)) {
							pinst->v_errorCode = result;
							fbcomlib_FBComCommon_state_set(
								Ov_StaticPtrCast(fbcomlib_FBComCommon, pinst),
								FBCOMLIB_STATE_INTERNAL_ERROR);
							Throw(result);
						}
						result = ov_string_setvalue(&(pinst->p_apiSet.v_path),
							pinst->v_path);
						if(Ov_Fail(result)) {
							pinst->v_errorCode = result;
							fbcomlib_FBComCommon_state_set(
								Ov_StaticPtrCast(fbcomlib_FBComCommon, pinst),
								FBCOMLIB_STATE_INTERNAL_ERROR);
							Throw(result);
						}
					}
					if(pinst->v_sendRequested || pinst->v_doCyclic) { /*	send Requested or cyclic sending requested	*/
						if(pinst->v_doCyclic)
							pinst->p_apiSet.v_holdConnection = TRUE;
						else
							pinst->p_apiSet.v_holdConnection = FALSE;
						result = Ov_SetAnyValue(&(pinst->p_apiSet.v_varValue),
							&(pinst->v_sendVar));
						if(Ov_Fail(result)) {
							pinst->v_errorCode = result;
							fbcomlib_FBComCommon_state_set(
								Ov_StaticPtrCast(fbcomlib_FBComCommon, pinst),
								FBCOMLIB_STATE_INTERNAL_ERROR);
							Throw(result);
						}
						/* refreshing */
						sync_syncVars_refreshVars(pinst);
						// remove not changed vars
						if(pinst->v_diffBased)
							sync_syncVars_seperateUnchangedVars(pinst);
						/* send */
						pVtblSetVar->m_submit(
							Ov_StaticPtrCast(ksapi_KSApiCommon, &(pinst->p_apiSet)));
						/* update LastChanged */
						updateLastChanged(pinst);
						fbcomlib_FBComCommon_state_set(
							Ov_StaticPtrCast(fbcomlib_FBComCommon, pinst),
							FBCOMLIB_STATE_WAITING);
						pinst->v_requestSendTime = *pltc;
						pinst->v_sendRequested = FALSE;
						return;
					}
					return;
				} else if(pinst->v_state != FBCOMLIB_STATE_WRONGINPUT) {
					if(pinst->v_doCyclic && pinst->v_retryAfter) {
						if(pltc->secs
								> (pinst->v_requestSendTime.secs + pinst->v_retryAfter)) {
							if(pinst->v_doReset) fbcomlib_setVar_doReset_set(pinst, FALSE);
							fbcomlib_setVar_doReset_set(pinst, TRUE);
							fbcomlib_setVar_doReset_set(pinst, FALSE);
							fbcomlib_FBComCommon_doCyclic_set(
								Ov_StaticPtrCast(fbcomlib_FBComCommon, pinst), TRUE);
						}

					}
				}
				return;
			}
				Catch(err)
	{
		switch (err) {
			case OV_ERR_BADPARAM:
				ov_logfile_error("syncVars cexp: bad param");
				pinst->v_result = err;
				break;
			default:
				ov_logfile_error("syncVars cexp: failed error: %s",
					ov_result_getresulttext(err));
				pinst->v_result = 1;
		}
	}
	return;
}

