
/******************************************************************************
*
*   FILE
*   ----
*   Upload.c
*
*   History
*   -------
*   2018-03-23   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_CTree
#define OV_COMPILE_LIBRARY_CTree
#endif


#include "CTree.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT void CTree_Upload_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_CTree_Upload pinst = Ov_StaticPtrCast(CTree_Upload, pfb);

    return;
}

