
/******************************************************************************
*
*   FILE
*   ----
*
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_PostSys
#define OV_COMPILE_LIBRARY_PostSys
#endif


#include "PostSys.h"
#include "libov/ov_association.h"

#include "libov/ov_macros.h"

OV_IMPL_LINK(PostSys_MsgDelivery2CurrentMessage)
OV_IMPL_UNLINK(PostSys_MsgDelivery2CurrentMessage)
OV_IMPL_GETACCESS(PostSys_MsgDelivery2CurrentMessage)

