
/******************************************************************************
*
*   FILE
*   ----
*   reqSender.c
*
*   History
*   -------
*   2018-12-28   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_lbalance
#define OV_COMPILE_LIBRARY_lbalance
#endif


#include "lbalance.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_UINT lbalance_reqSender_outLoad_get(
    OV_INSTPTR_lbalance_reqSender          pobj
) {
    return pobj->v_outLoad;
}

OV_DLLFNCEXPORT OV_RESULT lbalance_reqSender_outLoad_set(
    OV_INSTPTR_lbalance_reqSender          pobj,
    const OV_UINT  value
) {
    pobj->v_outLoad = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT lbalance_reqSender_R_set(
    OV_INSTPTR_lbalance_reqSender          pobj,
    const OV_BOOL  value
) {
    pobj->v_R = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void lbalance_reqSender_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_lbalance_reqSender pinst = Ov_StaticPtrCast(lbalance_reqSender, pfb);

    return;
}

