
/******************************************************************************
*
*   FILE
*   ----
*   Transport.c
*
*   History
*   -------
*   2018-03-20   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_CTree
#define OV_COMPILE_LIBRARY_CTree
#endif


#include "CTree.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT void CTree_Transport_submit(
		OV_INSTPTR_CTree_CTreeCommon	 			pobj
	) {
    /*    
    *   local variables
    */

    return;
}

