
/******************************************************************************
*
*   FILE
*   ----
*   TreeJSON.c
*
*   History
*   -------
*   2018-01-25   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_CTree
#define OV_COMPILE_LIBRARY_CTree
#endif


#include "CTree.h"
#include "libov/ov_macros.h"
#include "string.h"
#include "cJSON.h"


OV_DLLFNCEXPORT OV_BOOL CTree_TreeJSON_variables_get(
    OV_INSTPTR_CTree_TreeJSON          pobj
) {
    return pobj->v_variables;
}

OV_DLLFNCEXPORT void CTree_TreeJSON_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_CTree_TreeJSON pinst = Ov_StaticPtrCast(CTree_TreeJSON, pfb);
    OV_RESULT res;
    OV_STRING tmp = "abcde";
    res = strget(&pinst->v_tree, tmp, 2, -1);
    pinst->v_resstat = res;
    return;
}

