/******************************************************************************
 *
 *   FILE
 *   ----
 *   dijkstraTest.c
 *
 *   History
 *   -------
 *   2018-07-16   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/

#ifndef OV_COMPILE_LIBRARY_TGraphTest
#define OV_COMPILE_LIBRARY_TGraphTest
#endif

#include "TGraphTest.h"
#include "libov/ov_macros.h"
#include "dijkstra.h"
#include "CException.h"

#include "unity.h"
#include "unity_fixture.h"

#include "ovunity.h"
#include "ovunity_helper.h"


OV_INSTPTR_TGraphTest_dijkstraTest gpinst;
OV_INSTPTR_TGraph_graph gpobj;
OV_TIME *gpltc;

TEST_GROUP( dijkstra);

TEST_SETUP( dijkstra) {
	ov_memstack_lock();
	//This is run before EACH TEST
//	ov_string_setvalue(&gpinst->v_start, "PE004");
//	ov_string_set_vecvalue_one(&gpinst->v_recipe, 1, "PE005");
//	gpinst->v_EN = 0;
}

TEST_TEAR_DOWN( dijkstra) {
	ov_memstack_unlock();
}

TEST( dijkstra, dijkstra_default) {
	load_test_data("TGraphTest", "default.json");
	OV_INSTPTR_TGraph_Node source = ov_path_getobjectpointer("/TechUnits/TGraphTest.obj.Nodes/PE025_0",2);
	OV_INSTPTR_TGraph_Node target = ov_path_getobjectpointer("/TechUnits/TGraphTest.obj.Nodes/PE021_0",2);;
	dijkstra_get_path(gpobj, source, target);
}

TEST_GROUP_RUNNER( dijkstra) {
	RUN_TEST_CASE(dijkstra, dijkstra_default);
}

static void RunAllTests(void) {
	RUN_TEST_GROUP(dijkstra);
}

OV_DLLFNCEXPORT void TGraphTest_dijkstraTest_typemethod(
		OV_INSTPTR_fb_functionblock pfb, OV_TIME *pltc) {
	/*
	 *   local variables
	 */
	OV_INSTPTR_TGraphTest_dijkstraTest pinst = Ov_StaticPtrCast(
		TGraphTest_dijkstraTest, pfb);
	gpinst = Ov_StaticPtrCast(TGraphTest_dijkstraTest, pfb);
	gpobj = &gpinst->p_obj;
	gpltc = pltc;

	const char* argv[] = { "dijkstra", "-v" };
	CEXCEPTION_T e;
	Try
			{
				UnityMain(2, argv, RunAllTests);
			}
				Catch(e)
	{
		ov_logfile_error("mega catch");
	}
	return;
}

